@baseUrl = http://localhost:3000

### Health
GET {{baseUrl}}/

### List posts
GET {{baseUrl}}/posts

### Create post
POST {{baseUrl}}/posts
Content-Type: application/json

{
  "title": "My first post",
  "body": "Hello from REST client",
  "sender": "Niv"
}

# Get a single post by ID
GET http://localhost:3000/posts/6738b7b2944556561a86110a